// <auto-generated />
namespace TSModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class forign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forign));
        
        string IMigrationMetadata.Id
        {
            get { return "202002011211368_forign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
